version: '3.4'

services:
  database:
    image: 'mongo'
    container_name: 'my-mongo'
    ports:
      - '27017-27019:27017-27019'

  src:
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - .:/home/
    stdin_open: true
    tty: true