version: '3.4'

services:
  database:
    image: 'mongo'
    container_name: 'my-mongo'
    ports:
      - '27017-27019:27017-27019'

  scraper:
    build:
      context: ./scraper
    container_name: 'my-scraper'
    command: /bin/bash
    volumes:
      - ./scraper:/home
    stdin_open: true
    tty: true
  
  analysis:
    build:
      context: ./analysis
    container_name: 'my-analysis'
    volumes: 
      - ./analysis:/home
    stdin_open: true
    tty: true